In [ ]:
#pip install numpy

In [1]:
import numpy as np

In [8]:
#1 Dimensional Array
a=np.array([4,7,8,5,4,5,5,9])

In [9]:
a

array([4, 7, 8, 5, 4, 5, 5, 9])

In [10]:
#It is an ndarray, i.e. n-dimensional array
type(a)

numpy.ndarray

In [11]:
a.shape

(8,)

In [12]:
#2 Dimensional Array
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a.shape

(3, 2)

In [14]:
a=np.array([[1,2,8,6],[9,10,3,4],[5,6,6,2]])
a

array([[ 1,  2,  8,  6],
       [ 9, 10,  3,  4],
       [ 5,  6,  6,  2]])

In [15]:
a.shape

(3, 4)

In [16]:
a[1,1]

10

In [17]:
a[2,3]

2

In [18]:
a[2,0]

5

In [19]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
a=np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
a=np.arange(5,12)
a

array([ 5,  6,  7,  8,  9, 10, 11])

In [23]:
a=np.arange(3,50,5)
a

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [25]:
#16,15,14....6,5,4,3,2,1
a=np.arange(16,2,-3)
a**3

array([16, 13, 10,  7,  4])

Create a dataframe using numpy array structure, with 3 columns,

1st col- squares of 1st 10 natural numbers

2nd col- cubes of 1st 10 natural numbers

3rd col- mean of the 1st 2 columns

In [29]:
d1= [1,2,3,4,5,6,7,8,9,10]
a=[number**2 for number in d1]
b=[number**3 for number in d1]
c=np.mean(a and b)
d=np.array([[a],[b],[c]])
d

<ipython-input-29-fe0b81975bb2>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  d=np.array([[a],[b],[c]])


array([[list([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])],
       [list([1, 8, 27, 64, 125, 216, 343, 512, 729, 1000])],
       [302.5]], dtype=object)

In [27]:
a=np.square(np.arange(1,11))
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [ ]:
a1=np.arange(1,11)
a1=a1*a1
a2=np.arange(1,11)
a2=a2**3
a3=(a1+a2)/2
a3
import pandas as pd 
df=pd.DataFrame(columns=['a1','a2','a3'])
df['a1']=pd.Series(a1)
df['a2']=pd.Series(a2)
df['a3']=pd.Series(a3)
df

In [ ]:
import pandas as pd
df=pd.DataFrame(columns=['Squares', 'Cubes', 'Mean'])
df['Squares']=pd.Series(np.arange(1,11)**2)
df['Cubes']=pd.Series(np.arange(1,11)**3)
df['Mean']=pd.Series(((np.arange(1,11)**2)+(np.arange(1,11)**3))/2)
df


In [ ]:
import pandas as pd
a=np.arange(1,11)
print(a)
b=[]
for i in a:
    b.append(i*i)
print(b)
x=pd.Series(b)    
x

In [ ]:
a=np.arange(1,11)
b=[]
for i in a:
    b.append(i*i*i)
y=pd.Series(b)    
y  

In [ ]:
z=(x+y)/2
z

In [ ]:
frame={'x':x, 'y':y, "z":z }
result=pd.DataFrame(frame)
result

In [ ]:
a=([[0,11]])
for a in range(1,11):
    print(a*a*a, end= ",")

In [ ]:
a = np.arange(0,11)
a*a*a

In [ ]:
#linspace
a=np.linspace(2,16,6)
a

#2 , , , , , 16

In [ ]:
a=np.linspace(2,20,9)
a

#2..........20

In [ ]:
b=np.zeros(8)
b

In [ ]:
#5 is the number of times array is repeated
#3 is the number of rows per array
#4 is the number of columns per array
c=np.zeros((5,3,4))
c

In [30]:
a=np.array([[8,7,5],[10,3,9],[2,8,4]])
a

array([[ 8,  7,  5],
       [10,  3,  9],
       [ 2,  8,  4]])

In [34]:
a[:,1]

array([7, 3, 8])

In [35]:
a[2,:]

array([2, 8, 4])

In [ ]:
#Axis 0 = Column-wise
#Axis 1 = Row-wise

In [31]:
a.max(axis=0)

array([10,  8,  9])

In [32]:
a.max(axis=1)

array([ 8, 10,  8])

In [ ]:
a.min(axis=0)

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)

In [33]:
#Column-wise sum values
a.sum(axis=0)

array([20, 18, 18])

In [36]:
# Row-wise sum values
a.sum(axis=1)

array([20, 22, 14])

In [ ]:
#Square Root the entire array
a=np.array([[2,1,5],[8,3,9]])
print(a)
np.sqrt(a)

In [ ]:
#To find square root of a specific element, e.g. 8
print(a)
print(a[1,0])
np.sqrt(a[1,0])

In [ ]:
#To find square root of entire row 2
print(a)
np.sqrt(a[1,:])

In [ ]:
#To find square root of entire column 1
print(a)
np.sqrt(a[:,0])

In [ ]:
np.log(a)

Log of a number to a base defined will give us the number to which the base must be raised to get the value for which we are finding the log 

Log of 'a' to the base 'b' will give us the power of 'b', for which the result will be 'a' 
log of 4 to the base 2

### Natural log

log of 5 will give us the power of e (constant) which gives the output as 5. 

e=2.718

In [ ]:
a = np.array([[2,3,3,4],[3,4,4,4],[5,6,2,3],[7,8,4,4]])
print(a)
np.square(a)

In [ ]:
np.cumsum(a)

In [ ]:
a = np.arange(51)
print(a)
np.cumsum(a)

In [ ]:
a = np.arange(0,50.5,.5)
print(a)
np.cumsum(a)

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

In [ ]:
#What if we try to add arrays with different dimensions i.e. unequal number of rows/columns?
a=np.array([[1,5,3],[6,2,4],[7,8,9]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)
a+b

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])

print(a)
print(b)
a-b

In [ ]:
print(a)
print(b)
a*b

In [ ]:
print(a)
print(b)
a/b

In [ ]:
print(a)
print(b)

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,7],[4,3,1]])
print(a)
print(b)

For a vertical stack, i.e. placing the array elements of a & b one below the other, we must have equal number of columns in both the arrays to be stacked

In [ ]:
np.vstack((a,b))

For a horizontal stack, i.e. placing the array elements of a & b next to each other, we must have equal number of rows in both the arrays to be stacked

In [ ]:
np.hstack((a,b))

In [ ]:
a=np.array([[1,5,3],[6,2,4]])
b=np.array([[8,5,8,6],[4,3,7,9]])
print(a)
print(b)

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [ ]:
array1=np.arange(15).reshape(3,5)
array1

In [ ]:
array1=np.arange(30).reshape(5,6)
array1

In [ ]:
array1[3][2]=14
array1

In [ ]:
a=np.array([[4,8,7,5,6,1,4,8,7,4]])
b=np.unique(a)
b

In [ ]:
import numpy as np
a=np.array([[4,8,7,5,6],[1,4,8,7,4]])
a

In [ ]:
b=a.transpose()
b

In [ ]:
a=np.array([2,5,4,6,7,8])
b=np.array([4,7,8,5,4,4])
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
c=np.concatenate((b,a))
c

In [ ]:
a=np.array([[2,5,4],[6,7,8]])
b=np.array([[4,7,8],[5,4,4]])

In [ ]:
print(a)
print(b)

In [ ]:
c=np.concatenate((a,b))
c

In [ ]:
help(np.allclose)

In [ ]:
import numpy as np
Array1=np.linspace(3,5,5)
print(Array1)
Array2=np.linspace(4,5,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
np.

In [ ]:
np.equal(Array1,Array2)

In [ ]:
Array1=np.linspace(3,6,5)
print(Array1)
Array2=np.linspace(4,9,5)
print(Array2)
np.greater_equal(Array1,Array2)

In [ ]:
Array1=np.empty((3,2),dtype=int)
Array1

In [ ]:
Array1=np.ones((3,6),dtype=int)
Array1

In [ ]:
l=[1,5,7,5,5,7,4]
arr=np.asarray(l)
arr

In [ ]:
l=[1,5,[7,5],5,7,4]
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
l=(4,7,8,5,1,4,6)
arr=np.asarray(l)
arr

In [ ]:
type(arr)

In [ ]:
Dict_1 = {d: "ABC", e : "DEF" , f: "GHI"}
Dict_1

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4,5])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a*b
c

In [ ]:
d=a+b
d

In [ ]:
a=np.array([4,5,2,1,7,8,6,3,4])
b=np.array([8,5,4,1,3,9,8,5,2,1])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[4,7,2,1]])
b=np.array([4,7,8,5])
c=a+b
c

In [ ]:
a=np.array([[1,2,3,5],[5,8,9,7],[8,2,4,6]])
a

In [ ]:
for x in np.nditer(a):
    print(x,end=' ')

In [ ]:
for x in np.nditer(a):
    print(x)

In [ ]:
print(a)

In [ ]:
# 'T' stands for transpose... It will change rows to columns & columns to rows.
trans_a=a.T
trans_a

In [ ]:
np.char.add(['Welcome','to'],['Python','Session'])

In [ ]:
np.add([2,3],[5,8])

In [ ]:
np.char.multiply("Hello",5)

In [ ]:
print(np.char.center('Python Session',30,'+'))
np.char.center('Python Session',30,'+')

In [ ]:
np.char.capitalize('welcome to python session')          

In [ ]:
np.char.title('welcome to python session')

In [ ]:
np.char.upper('welcome to python session')

In [ ]:
np.char.lower('WELCOME TO PYTHON SESSION')

In [ ]:
np.char.split("Welcome to Python Session")

In [ ]:
print(np.char.splitlines("Welcome\nto\nPython\nSession"))

In [ ]:
print(np.char.strip("        Welcome\nto\nPython\nSession     "))

In [ ]:
print(np.char.join('-','HMNSGD'))

In [ ]:
s='Welcome to Python Session'
s

In [ ]:
import numpy as np

In [ ]:
print(s)
print(np.char.replace(s,"Welcome to ","www."))

In [ ]:
t='Hello Neha, welcome to the class'
print(t)
print(np.char.replace(t,"class","party"))

In [ ]:
arr = np.array([12.2021, 90.23120, 123.0203, 23.202])
np.around(arr, 2)

In [ ]:
arr=np.array([12.45158,45.786546,7.8415868,5.486,4.8])
np.around(arr,3)

In [ ]:
np.floor(arr)

In [ ]:
np.ceil(arr)

In [ ]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]])
np.amin(a)
np.amin(a)
np.amin(a,0)
np.amax(a,0)
np.amin(a,1)
np.amax(a,1)

In [ ]:
a=np.array([[2,10,20],[80,43,31],[22,43,10]])
a

In [ ]:
np.amax(a,1)

In [ ]:
np.ptp(a,1)
np.ptp(a,0)


In [ ]:
#Peak to peak

In [ ]:
a

In [ ]:
np.ptp(a,1)

In [ ]:
a=np.array([[1,4],[5,3]])
a

In [ ]:
np.sum(a,axis=1)

In [ ]:
a=np.random.rand(5,2)
a

In [ ]:
a=np.random.randint(5, size=(5,6))
a

In [ ]:
np.array([1.+0.j, 2.+0.j, 3.+0.j],dtype=float)

In [ ]:
np.mat(np.array([1,2,3,4]))

In [ ]:
np.mat(np.array([[1,4,5],[7,8,9]]))

In [ ]:
np.mat('1 2;3 4;8 9')

In [ ]:
a=[7,4,5,6,9]
type(a)

In [ ]:
type(np.asarray(a))

In [ ]:
type(a)

In [ ]:
issubclass(np.matrix,np.ndarray)

In [ ]:
issubclass(np.ndarray,np.matrix)

In [ ]:
a=[1,2,3]
type(a)

In [ ]:
np.asanyarray(a)

In [ ]:
a=np.matrix([1,2,3,4])
a

In [ ]:
np.asanyarray(a)

In [ ]:
x=np.array([1,2,3])
x

In [ ]:
y=x

In [ ]:
y

In [ ]:
y[1]=45

In [ ]:
y

In [ ]:
x

In [ ]:
x[0]=89
x

In [ ]:
y

In [ ]:
x=[1,2,3]
x

In [ ]:
z=np.copy(x)
z

In [ ]:
x[2]=8435486
x

In [ ]:
z

In [ ]:
z[2]=89
z

In [ ]:
x

In [ ]:
np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)

In [ ]:
i=np.mat(np.array([[0,0,0],[1,1,1],[2,2,2]]))
i

In [ ]:
j=np.mat(np.array([[0,1,2],[0,1,2],[0,1,2]]))
j

In [ ]:
print(i)
print(j)
k=np.array([['00','01','02'],['10','11','12'],['20','21','22']])
print(k)

In [ ]:
np.fromfunction(lambda i,j: i*j,(3,3),dtype=int)

In [ ]:
np.fromfunction(lambda i,j,k: i*j*k,(3,3,3),dtype=int)

In [ ]:
list(range(5))
iterable=(x*x for x in range(5))

In [ ]:
iterable

In [ ]:
np.fromiter(iterable,float)

In [ ]:
list(range(5))

Create a list of a few temperature values in celcius (between 30 to 45 degrees)
Using 'for' loop, create another list where the celcius temperatures are converted into fahrenheit.

C*(9/5)+32=F

After converting to fahrenheit, create a dataframe with one column showing the above temperatures in celcius,and the nect column showing fahrenheit values for the given temperatures.

In [ ]:
import numpy as np
import pandas as pd
C=np.arange(30,45,2)
print(C)
F=[]
for i in (C,F):
    F=C*(9/5)+32
    
print(F)

TEMPERATURE={"C":C, "F":F}
result=pd.DataFrame(TEMPERATURE)
result

In [ ]:
import pandas as pd
import numpy as np
import random 
df = pd.DataFrame(columns=['C','F'])
x=list(np.random.randint(30,45, size=(5)))
y=[]
for i in x:
    f=i*(9/5)+32
    y.append(f)
df['C']=pd.Series(x)
df['F']=pd.Series(y)
df

In [ ]:
a=np.random.randint(2,40,size=(5))
print(a)
b=np.linspace(6,9,2)
print(b)
np.less_equal(a,b)